services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: javasecscan
      POSTGRES_USER: javasecscan
      POSTGRES_PASSWORD: javasecscan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/javasecscan
      SPRING_DATASOURCE_USERNAME: javasecscan
      SPRING_DATASOURCE_PASSWORD: javasecscan
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"

volumes:
  pgdata:
